
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


api:
  url:
    inventory: localhost:8082
    inventory: localhost:8082

server:
  port: 8081

<<<<<<< HEAD
=======
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: monolith
          destination: labshopmonolith
          contentType: application/json
        event-out:
          destination: labshopmonolith
          contentType: application/json

api:
  url:
    inventory: inventory:8080
    inventory: inventory:8080

>>>>>>> origin/template
